### ISSUE TITLE
Adding "jsonnet fmt" execution at save and autosave time would be very useful

### ISSUE THREAD

**Issue by ahakanbaba** [google/vim-jsonnet#2]
Hi all, 
has there been a discussion about adding auto "jsonnet fmt" execution at save time ? 
The [vim-go](https://github.com/fatih/vim-go)  has that feature for go using gofmt. It is very useful. 

A tool based resolution of spacing and formatting implementation saves a lot of thought cycles while writing code. More importantly it deems all kind of "tabs vs spaces" discussions  amongst team members useless. 

Something similar has already been implemented in [here](https://github.com/fatih/vim-go/blob/master/autoload/go/fmt.vim). vim-jsonnet could implement something similar. 

I am creating this issue to get a sense/reaction about this feature. In our team we had a real discussion about jsonnet coding conventions and wished a simple tool based, IDE integrated enforcement was available. 

In addition, if you know about the roadmap of "jsonnet fmt" please comment. Could we rely on that tool ? Does the jsonnet project plan to maintain the auto formatter ? I see that @sparkprime has done the [fomatter.cpp ](https://github.com/google/jsonnet/blame/master/core/formatter.cpp)

Thanks

**Comment by sparkprime** [comment]
This seems like a good idea.  I welcome a PR to add this, the default (on/off) being consistent with whatever vim-go does as the default since using vim-jsonnet is opt-in anyway.  The big question is what options to call jsonnet fmt with, and how are they customized?

jsonnet fmt is a core part of Jsonnet and will be maintained with the same priority as Jsonnet itself.

Also note that jsonnet fmt is quite extensible (visitor pattern) and PRs for adding new formatting rules are welcome (although any change to the default behavior will be reviewed quite thoroughly as it could have far-reaching consequences).

thanks

**Comment by ahakanbaba** [comment]
While being strongly inspired by [this](https://github.com/fatih/vim-go/blob/master/autoload/go/fmt.vim) we recommend the following parameters, switches. 

g:jsonnet_command = "jsonnet"
// This is the name of the binary

 g:jsonnet_fmt_command = "fmt"
// This is the <cmd> passed to the binary. 

This is slightly different from vim-go. There gofmt is one binary. In jsonnet we execute `jsonnet fmt`
These two flags make this extension flexible enough. 
If anything changes in the underlying tools, one could merely change the g:jsonnet_command and g:jsonnet_fmt_command in their .vimrc file and continue to use this extension. 

 g:jsonnet_fmt_options = ''
// Further optional user specified options to the jsonnet fmt comment 


I have very recently started to use jsonnet. I do not know the general desired formatting sentiments in the community. Please give suggestions if you want us to change anything in the following default flags. 

We propose to have the "-n 4 -i" as default, this leaves all flags default to `jsonnet fmt` except the indentation. 
  -n / --indent <n>       Number of spaces to indent by (default 0, means no change)
We have selected 4 arbitrarily. If you think, say 3 is a better indentation we could change. 
-i ( Update the Jsonnet file in place.)  makes the implementation easier. It does not have user facing impact anyways. 

Again, please note, the user has the freedom to override these with g:jsonnet_fmt_options in their vimrc file.

We have taken a first shot at implementing this. It looks pretty reasonable. We should be half way there to add this feature request in OSX environment. 

We will follow up with a Pull Request in the following days. 

Regards.
